/* ============================================================
   Word bank — ships inside the app (no network).
   Each category → list of entries. Each entry: a secret `word`
   and a pool of vague `clues` (one assigned per imposter, all
   different). Clues describe the word fairly without naming it.

   Full build: 10 categories, 20 entries each, same shape.
   ============================================================ */

const BANK = {
  "Everyday Objects": [
    { word: "Pillow",      clues: ["soft", "sleep", "rest", "fluff"] },
    { word: "Toothbrush",  clues: ["bristles", "morning", "clean", "handle"] },
    { word: "Scissors",    clues: ["cut", "blades", "snip", "paper"] },
    { word: "Candle",      clues: ["wax", "flame", "scent", "melt"] },
    { word: "Backpack",    clues: ["straps", "carry", "school", "zip"] },
    { word: "Remote",      clues: ["buttons", "channels", "couch", "point"] },
    { word: "Hammer",      clues: ["nails", "tool", "strike", "wood"] },
    { word: "Wallet",      clues: ["cards", "pocket", "cash", "fold"] },
    { word: "Clock",       clues: ["time", "tick", "hands", "wall"] },
    { word: "Bucket",      clues: ["water", "carry", "handle", "fill"] },
    { word: "Pencil",      clues: ["write", "graphite", "eraser", "sketch"] },
    { word: "Spoon",       clues: ["soup", "scoop", "metal", "stir"] },
    { word: "Comb",        clues: ["hair", "teeth", "groom", "part"] },
    { word: "Stapler",     clues: ["office", "press", "paper", "bind"] },
    { word: "Sponge",      clues: ["soak", "wash", "porous", "dishes"] },
    { word: "Flashlight",  clues: ["beam", "dark", "battery", "torch"] },
    { word: "Key",         clues: ["lock", "metal", "unlock", "door"] },
    { word: "Blanket",     clues: ["warm", "cover", "cozy", "bed"] },
    { word: "Notebook",    clues: ["pages", "notes", "spiral", "write"] },
    { word: "Kettle",      clues: ["boil", "spout", "steam", "tea"] },
  ],
  "Food & Drinks": [
    { word: "Pancakes",    clues: ["stack", "syrup", "breakfast", "flat"] },
    { word: "Sushi",       clues: ["rice", "raw", "roll", "Japan"] },
    { word: "Burger",      clues: ["bun", "patty", "stack", "grill"] },
    { word: "Spaghetti",   clues: ["pasta", "twirl", "sauce", "strands"] },
    { word: "Chocolate",   clues: ["cocoa", "sweet", "bar", "melt"] },
    { word: "Lemonade",    clues: ["sour", "summer", "yellow", "refresh"] },
    { word: "Popcorn",     clues: ["pop", "cinema", "kernels", "butter"] },
    { word: "Pineapple",   clues: ["tropical", "spiky", "yellow", "sweet"] },
    { word: "Tacos",       clues: ["shell", "fold", "Mexico", "fillings"] },
    { word: "Smoothie",    clues: ["blend", "fruit", "thick", "straw"] },
    { word: "Donut",       clues: ["ring", "glaze", "fried", "sweet"] },
    { word: "Cheese",      clues: ["dairy", "yellow", "aged", "melt"] },
    { word: "Watermelon",  clues: ["summer", "seeds", "juicy", "green"] },
    { word: "Pretzel",     clues: ["twist", "salt", "knot", "baked"] },
    { word: "Milkshake",   clues: ["thick", "cold", "blend", "straw"] },
    { word: "Curry",       clues: ["spice", "sauce", "warm", "aroma"] },
    { word: "Waffle",      clues: ["grid", "syrup", "crisp", "breakfast"] },
    { word: "Strawberry",  clues: ["red", "seeds", "sweet", "berry"] },
    { word: "Noodles",     clues: ["slurp", "bowl", "broth", "strands"] },
    { word: "Honey",       clues: ["bees", "golden", "sticky", "sweet"] },
  ],
  "Animals": [
    { word: "Giraffe",     clues: ["tall", "neck", "spots", "savanna"] },
    { word: "Kangaroo",    clues: ["hop", "pouch", "Australia", "tail"] },
    { word: "Dolphin",     clues: ["smart", "ocean", "leap", "playful"] },
    { word: "Cheetah",     clues: ["fast", "spots", "sprint", "savanna"] },
    { word: "Octopus",     clues: ["eight", "ink", "ocean", "suckers"] },
    { word: "Crocodile",   clues: ["river", "jaws", "scales", "lurk"] },
    { word: "Peacock",     clues: ["feathers", "display", "blue", "fan"] },
    { word: "Hedgehog",    clues: ["spines", "curl", "small", "night"] },
    { word: "Camel",       clues: ["desert", "hump", "sand", "thirst"] },
    { word: "Koala",       clues: ["tree", "sleepy", "Australia", "leaves"] },
    { word: "Flamingo",    clues: ["pink", "stand", "wade", "curve"] },
    { word: "Rhino",       clues: ["horn", "thick", "charge", "grey"] },
    { word: "Tiger",       clues: ["stripes", "orange", "jungle", "prowl"] },
    { word: "Bat",         clues: ["night", "wings", "cave", "fly"] },
    { word: "Frog",        clues: ["hop", "pond", "green", "croak"] },
    { word: "Wolf",        clues: ["pack", "howl", "forest", "fang"] },
    { word: "Seahorse",    clues: ["tiny", "curl", "ocean", "drift"] },
    { word: "Panda",       clues: ["bamboo", "black", "China", "round"] },
    { word: "Eagle",       clues: ["soar", "talons", "sky", "sharp"] },
    { word: "Snail",       clues: ["slow", "shell", "slime", "trail"] },
  ],
  "Places": [
    { word: "Museum",      clues: ["art", "history", "quiet", "exhibits"] },
    { word: "Stadium",     clues: ["crowd", "sport", "seats", "cheer"] },
    { word: "Volcano",     clues: ["lava", "erupt", "mountain", "heat"] },
    { word: "Desert",      clues: ["sand", "dry", "heat", "dunes"] },
    { word: "Castle",      clues: ["stone", "king", "towers", "moat"] },
    { word: "Jungle",      clues: ["dense", "vines", "wild", "humid"] },
    { word: "Bakery",      clues: ["bread", "aroma", "oven", "sweet"] },
    { word: "Cinema",      clues: ["screen", "dark", "seats", "film"] },
    { word: "Waterfall",   clues: ["rush", "cliff", "mist", "drop"] },
    { word: "Aquarium",    clues: ["glass", "fish", "tanks", "blue"] },
    { word: "Pyramid",     clues: ["Egypt", "ancient", "stone", "tomb"] },
    { word: "Lighthouse",  clues: ["beam", "coast", "tower", "guide"] },
    { word: "Farm",        clues: ["crops", "barn", "animals", "fields"] },
    { word: "Mountain",    clues: ["peak", "climb", "snow", "high"] },
    { word: "Subway",      clues: ["underground", "trains", "tunnel", "commute"] },
    { word: "Zoo",         clues: ["cages", "animals", "visit", "exhibits"] },
    { word: "Cave",        clues: ["dark", "rock", "echo", "deep"] },
    { word: "Market",      clues: ["stalls", "trade", "busy", "fresh"] },
    { word: "Gym",         clues: ["weights", "sweat", "fitness", "machines"] },
    { word: "Island",      clues: ["surrounded", "shore", "remote", "palm"] },
  ],
  "Singing Artists": [
    { word: "Adele",         clues: ["ballads", "powerful", "British", "emotion"] },
    { word: "Bruno Mars",    clues: ["retro", "funk", "smooth", "showman"] },
    { word: "Billie Eilish", clues: ["whisper", "young", "moody", "unique"] },
    { word: "Justin Bieber", clues: ["pop", "Canada", "teen", "hits"] },
    { word: "Doja Cat",      clues: ["viral", "playful", "rap", "quirky"] },
    { word: "Wizkid",        clues: ["afrobeats", "Nigeria", "smooth", "global"] },
    { word: "SZA",           clues: ["rnb", "soulful", "smooth", "dreamy"] },
    { word: "Chris Brown",   clues: ["dance", "rnb", "smooth", "moves"] },
    { word: "Dua Lipa",      clues: ["disco", "pop", "dance", "British"] },
    { word: "Kendrick Lamar",clues: ["rap", "lyrical", "deep", "respected"] },
    { word: "Sia",           clues: ["wig", "powerful", "anthems", "hidden"] },
    { word: "Lady Gaga",     clues: ["bold", "pop", "theatrical", "anthems"] },
    { word: "Travis Scott",  clues: ["rap", "energy", "hype", "autotune"] },
    { word: "Davido",        clues: ["afrobeats", "Nigeria", "party", "energy"] },
    { word: "Shakira",       clues: ["hips", "Latin", "dance", "Colombia"] },
    { word: "Post Malone",   clues: ["tattoos", "melodic", "genre", "chill"] },
    { word: "Olivia Rodrigo",clues: ["young", "heartbreak", "pop", "raw"] },
    { word: "Usher",         clues: ["rnb", "dance", "smooth", "confetti"] },
    { word: "Nicki Minaj",   clues: ["rap", "bold", "colorful", "fierce"] },
    { word: "Coldplay",      clues: ["band", "anthems", "British", "stadium"] },
  ],
  "Movies": [
    { word: "Frozen",          clues: ["ice", "sisters", "snow", "song"] },
    { word: "Forrest Gump",    clues: ["running", "feather", "life", "chocolates"] },
    { word: "The Matrix",      clues: ["code", "red", "reality", "simulation"] },
    { word: "Gladiator",       clues: ["arena", "Rome", "revenge", "warrior"] },
    { word: "Toy Story",       clues: ["toys", "playroom", "cowboy", "alive"] },
    { word: "The Lion King",   clues: ["savanna", "cub", "kingdom", "circle"] },
    { word: "Interstellar",    clues: ["space", "time", "wormhole", "love"] },
    { word: "Finding Nemo",    clues: ["ocean", "fish", "lost", "father"] },
    { word: "The Godfather",   clues: ["mafia", "family", "power", "shadows"] },
    { word: "Shrek",           clues: ["ogre", "swamp", "green", "fairytale"] },
    { word: "Harry Potter",    clues: ["wizard", "school", "wand", "scar"] },
    { word: "Up",              clues: ["balloons", "house", "old", "adventure"] },
    { word: "The Dark Knight", clues: ["bat", "city", "villain", "hero"] },
    { word: "Coco",            clues: ["music", "family", "marigold", "memory"] },
    { word: "Jaws",            clues: ["shark", "beach", "fear", "boat"] },
    { word: "Moana",           clues: ["ocean", "island", "voyage", "brave"] },
    { word: "Pirates",         clues: ["sea", "treasure", "ship", "curse"] },
    { word: "The Incredibles", clues: ["family", "powers", "mask", "team"] },
    { word: "Rocky",           clues: ["boxing", "underdog", "stairs", "fight"] },
    { word: "Aladdin",         clues: ["lamp", "wishes", "carpet", "genie"] },
  ],
  "Anime Shows": [
    { word: "Bleach",            clues: ["soul", "sword", "spirits", "orange"] },
    { word: "Hunter x Hunter",   clues: ["exam", "license", "quest", "friends"] },
    { word: "Fullmetal Alchemist", clues: ["alchemy", "brothers", "armor", "equivalent"] },
    { word: "Jujutsu Kaisen",    clues: ["curses", "sorcerers", "fingers", "school"] },
    { word: "Tokyo Ghoul",       clues: ["mask", "hunger", "city", "dark"] },
    { word: "Sailor Moon",       clues: ["moon", "transform", "guardians", "magic"] },
    { word: "One Punch Man",     clues: ["bald", "strongest", "bored", "hero"] },
    { word: "Black Clover",      clues: ["magic", "grimoire", "knights", "shout"] },
    { word: "Spy x Family",      clues: ["spy", "family", "telepath", "secret"] },
    { word: "Chainsaw Man",      clues: ["devils", "saw", "contract", "gritty"] },
    { word: "Code Geass",        clues: ["mecha", "rebellion", "command", "eye"] },
    { word: "Cowboy Bebop",      clues: ["bounty", "space", "jazz", "crew"] },
    { word: "Fairy Tail",        clues: ["guild", "magic", "dragon", "bonds"] },
    { word: "Mob Psycho",        clues: ["psychic", "calm", "spirits", "growth"] },
    { word: "Vinland Saga",      clues: ["vikings", "revenge", "sea", "war"] },
    { word: "Haikyuu",           clues: ["volleyball", "team", "jump", "school"] },
    { word: "Berserk",           clues: ["sword", "dark", "armor", "fate"] },
    { word: "Soul Eater",        clues: ["scythe", "academy", "souls", "moon"] },
    { word: "Dr Stone",          clues: ["science", "stone", "revival", "invent"] },
    { word: "Inuyasha",          clues: ["feudal", "jewel", "dog", "time"] },
  ],
  "Cartoons": [
    { word: "Scooby-Doo",        clues: ["dog", "mystery", "van", "snacks"] },
    { word: "Looney Tunes",      clues: ["rabbit", "carrot", "chase", "classic"] },
    { word: "Phineas and Ferb",  clues: ["summer", "invent", "brothers", "platypus"] },
    { word: "Gravity Falls",     clues: ["mystery", "twins", "journal", "town"] },
    { word: "Adventure Time",    clues: ["dog", "land", "quests", "magic"] },
    { word: "Family Guy",        clues: ["family", "baby", "satire", "dog"] },
    { word: "Dexters Laboratory", clues: ["genius", "secret", "lab", "sister"] },
    { word: "Courage",           clues: ["scared", "dog", "farm", "purple"] },
    { word: "Johnny Bravo",      clues: ["muscles", "hair", "ladies", "comb"] },
    { word: "Pinky and the Brain", clues: ["mice", "lab", "world", "plan"] },
    { word: "Teen Titans",       clues: ["heroes", "tower", "team", "young"] },
    { word: "Ed Edd n Eddy",     clues: ["trio", "scam", "cul-de-sac", "candy"] },
    { word: "Steven Universe",   clues: ["gems", "magic", "boy", "songs"] },
    { word: "Regular Show",      clues: ["park", "blue", "raccoon", "slack"] },
    { word: "The Flintstones",   clues: ["stone", "prehistoric", "town", "car"] },
    { word: "Kim Possible",      clues: ["spy", "teen", "gadgets", "mission"] },
    { word: "Hey Arnold",        clues: ["city", "football", "stoop", "kids"] },
    { word: "Tom and Jerry",     clues: ["cat", "mouse", "chase", "silent"] },
    { word: "DuckTales",         clues: ["ducks", "treasure", "uncle", "gold"] },
    { word: "Bluey",             clues: ["dog", "family", "play", "Australia"] },
  ],
  "Sports": [
    { word: "Basketball",  clues: ["hoop", "dribble", "court", "dunk"] },
    { word: "Soccer",      clues: ["goal", "kick", "pitch", "global"] },
    { word: "Tennis",      clues: ["racket", "net", "serve", "court"] },
    { word: "Swimming",    clues: ["pool", "lanes", "strokes", "water"] },
    { word: "Boxing",      clues: ["gloves", "ring", "punch", "rounds"] },
    { word: "Golf",        clues: ["clubs", "holes", "green", "swing"] },
    { word: "Cricket",     clues: ["bat", "wicket", "overs", "field"] },
    { word: "Rugby",       clues: ["oval", "scrum", "tackle", "try"] },
    { word: "Cycling",     clues: ["wheels", "pedal", "race", "helmet"] },
    { word: "Surfing",     clues: ["waves", "board", "ocean", "balance"] },
    { word: "Skiing",      clues: ["snow", "slopes", "poles", "downhill"] },
    { word: "Volleyball",  clues: ["net", "spike", "serve", "sand"] },
    { word: "Archery",     clues: ["bow", "arrow", "target", "aim"] },
    { word: "Baseball",    clues: ["bat", "diamond", "pitch", "bases"] },
    { word: "Skateboarding", clues: ["deck", "tricks", "ramp", "wheels"] },
    { word: "Wrestling",   clues: ["grapple", "mat", "pin", "hold"] },
    { word: "Badminton",   clues: ["racket", "shuttle", "net", "light"] },
    { word: "Gymnastics",  clues: ["flips", "beam", "balance", "flexible"] },
    { word: "Hockey",      clues: ["stick", "puck", "ice", "goal"] },
    { word: "Marathon",    clues: ["running", "endurance", "distance", "race"] },
  ],
  "Jobs": [
    { word: "Doctor",      clues: ["patients", "heal", "clinic", "coat"] },
    { word: "Teacher",     clues: ["class", "lessons", "board", "students"] },
    { word: "Chef",        clues: ["kitchen", "cook", "recipes", "plate"] },
    { word: "Pilot",       clues: ["cockpit", "sky", "fly", "wings"] },
    { word: "Firefighter", clues: ["flames", "hose", "rescue", "ladder"] },
    { word: "Plumber",     clues: ["pipes", "leaks", "wrench", "water"] },
    { word: "Lawyer",      clues: ["court", "case", "argue", "justice"] },
    { word: "Farmer",      clues: ["crops", "fields", "harvest", "barn"] },
    { word: "Electrician", clues: ["wires", "circuits", "power", "sparks"] },
    { word: "Dentist",     clues: ["teeth", "drill", "clean", "chair"] },
    { word: "Astronaut",   clues: ["space", "suit", "rocket", "orbit"] },
    { word: "Barber",      clues: ["hair", "trim", "chair", "razor"] },
    { word: "Journalist",  clues: ["news", "report", "story", "deadline"] },
    { word: "Mechanic",    clues: ["engine", "repair", "tools", "garage"] },
    { word: "Nurse",       clues: ["care", "patients", "ward", "scrubs"] },
    { word: "Photographer",clues: ["camera", "shots", "lens", "capture"] },
    { word: "Carpenter",   clues: ["wood", "build", "saw", "frame"] },
    { word: "Librarian",   clues: ["books", "quiet", "shelves", "order"] },
    { word: "Scientist",   clues: ["lab", "research", "experiment", "data"] },
    { word: "Police",      clues: ["badge", "law", "patrol", "siren"] },
  ],
};

const CATEGORIES = Object.keys(BANK);
